version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
    volumes:
      - ./.env:/app/.env
    ports:
      - 3000:3000
    networks:
      - irasshaimase-dev-net

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: irasshaimase
    volumes:
      - irasshaimase-dev-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - irasshaimase-dev-net

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    networks:
      - irasshaimase-dev-net

volumes:
  irasshaimase-dev-mysql:

networks:
  irasshaimase-dev-net:
